name: WPrecog
version: "0.1"
license: "GPL-2.0-or-later"
date: 2026-04-10
description: |
    provides constructive recognition algorithms for subgroups of wreath products via wreath product decompositions

authors:
    - name: Friedrich Rober
      url: mailto:friedrich.rober@rwth-aachen.de

maintainers:
    - name: Friedrich Rober
      url: mailto:friedrich.rober@rwth-aachen.de

GAP: ">= 4.12"

needed-pkgs:
    - name: "recog"
      version: ">= 1.3.2"
      url: "https://gap-packages.github.io/recog"

www: https://FriedrichRober.github.io/WPrecog/
readme: README.md
packageinfo: https://FriedrichRober.github.io/WPrecog/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/FriedrichRober/WPrecog/releases/download/v0.1/WPrecog-0.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Rob26</span>]   <b class='BibAuthor'>Rober, F.</b>,
     <i class='BibTitle'>WPrecog, provides constructive recognition algorithms for subgroups of wreath products via wreath product decompositions,
             Version 0.1</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://FriedrichRober.github.io/WPrecog/">https://FriedrichRober.github.io/WPrecog/</a></span>.
    </p>
    

bibtex: |
    @misc{ WPrecog,
      author =           {Rober, F.},
      title =            {{WPrecog},     provides    constructive    recognition
                          algorithms for subgroups of wreath products via wreath
                          product decompositions, {V}ersion 0.1},
      month =            {Apr},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href      {https://FriedrichRober.github.io/WPrecog/}
                          {\texttt{https://FriedrichRober.github.io/}\discretionary
                          {}{}{}\texttt{WPrecog/}}},
      printedkey =       {Rob26}
    }

